/**
 * @fileoverview Authentication database schema definitions for Better Auth integration.
 *
 * @description
 * This file contains Drizzle ORM schema definitions for the authentication system.
 * These schemas are automatically generated by Better Auth and define the database
 * structure for users, sessions, accounts, and verification tokens.
 *
 * @see {@link https://www.better-auth.com/docs/concepts/database Better Auth Database Documentation}
 *
 * @warning DO NOT MODIFY - This schema is auto-generated by Better Auth.
 * Any manual changes may be overwritten when regenerating the schema.
 *
 * @module auth.schema
 */

import { relations } from 'drizzle-orm';
import { pgTable, text, timestamp, boolean, index } from 'drizzle-orm/pg-core';

/**
 * User table schema - stores core user information.
 *
 * @description Auto-generated by Better Auth for user management.
 * Contains basic user profile data and authentication status.
 *
 */
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export type UserSchema = typeof user.$inferSelect;

/**
 * Session table schema - stores active user sessions.
 *
 * @description Auto-generated by Better Auth for session management.
 * Tracks user login sessions with expiration and device information.
 *
 */
export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
);

/**
 * Account table schema - stores OAuth and credential account information.
 *
 * @description Auto-generated by Better Auth for multi-provider authentication.
 * Links users to their authentication providers (OAuth, email/password, etc.).
 *
 */
export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
);

/**
 * Verification table schema - stores verification tokens.
 *
 * @description Auto-generated by Better Auth for email verification and password reset.
 * Manages temporary tokens for user verification workflows.
 *
 */
export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
);

/**
 * User relations definition.
 *
 * @description Defines the one-to-many relationships from user to sessions and accounts.
 * A user can have multiple active sessions and multiple linked accounts.
 */
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

/**
 * Session relations definition.
 *
 * @description Defines the many-to-one relationship from session to user.
 * Each session belongs to exactly one user.
 */
export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

/**
 * Account relations definition.
 *
 * @description Defines the many-to-one relationship from account to user.
 * Each account belongs to exactly one user.
 */
export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));
